api_platform:
    title: 'EventAPI'
    description: 'The EventAPI platform'
    version: '0.2.1'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
