doctrine:
    dbal:
        default_connection: default

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
            dbcache:
                url: '%env(resolve:DATABASE_CACHE_URL)%'


    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    App:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            dbcache:
                connection: dbcache
                mappings:
                    Cached:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Cached'
                        prefix: 'App\Cached'
                        alias: Cached